azure-pipelines.yml
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/MacCatalyst/Info.plist
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/iOS/Entitlements.plist
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/iOS/Info.plist

Similar PR for `CommunityToolkit.Maui`: https://github.com/CommunityToolkit/Maui/pull/158
This PR allows Azure Pipelines to build the iOS Sample App in `CommunityToolkit.Maui.Markup.Samples`.
Currently, `azure-pipelines.yml` only builds the Android + MacCatalyst version of the sample app:
```yml
#Note: Building iOS Sample App Requires Provisioning Profile
- task: CmdLine@2
displayName: 'Build Community Toolkit Sample'
inputs:
script: |
dotnet build $(PathToCommunityToolkitSampleCsproj) -c Release -f net6.0-android
dotnet build $(PathToCommunityToolkitSampleCsproj) -c Release -f net6.0-maccatalyst
```
This was done because building the iOS sample app without a Provisioning Profile would cause an error:
```bash
Build FAILED.
/Users/runner/.dotnet/packs/Microsoft.iOS.Sdk/15.0.101-preview.9.31 …
```

Enable iOS Builds in Azure Pipelines

---

azure-pipelines.yml
global.json
samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
samples/CommunityToolkit.Maui.Markup.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsPage.cs
samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/Windows/App.xaml.cs
samples/CommunityToolkit.Maui.Markup.Sample/Services/SettingsService.cs
samples/CommunityToolkit.Maui.Markup.Sample/ViewModels/NewsViewModel.cs

This PR adds support for .NET MAUI RC:
- Update CI Pipeline to use `6.0.300-preview.22204.3`
- Update `global.json` to use `6.0.300-preview.22204.3`
- Remove Windows-specific NuGet Packages
- Recommended in .NET MAUI's [Migrating-to-RC1](https://github.com/dotnet/maui/wiki/Migrating-to-RC1) docs
- Update Legacy Maui.Essentials Namespaces
- Temporarily Update `Build Sample App` step to only build `net6.0-android`
- Building `net6.0-ios` and `net6.0-maccatalyst` requires Xcode 13.3.1 which is not currently available on Azure Pipelines
We will need to update `CommunityToolkit.Maui.Markup.Sample` to use `CommunityToolkit.Maui v1.0.0-pre9` once the `CommunityToolkit.Maui` NuGet package has been released.
We will also need to remove `-f:net6.0-android` from the `Build Sample App` step once …

Support .NET MAUI RC

---

samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
samples/CommunityToolkit.Maui.Markup.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs

This PR re-adds the `CommunityToolkit.Maui` NuGet Package to `CommunityToolkit.Maui.Markup.Sample`.
Version 1.0.0-pre8 of this NuGet package had been temporarily removed after updating to .NET MAUI RC because of breaking changes in the Release Candidate.
Now that CommunityToolkit.Maui v1.0.0-pre9 (which targets .NET MAUI RC) has been published, we can add it back into the Sample App.

Re-Add `CommunityToolkit.Maui` to Sample App

---

samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsPage.cs
src/CommunityToolkit.Maui.Markup.UnitTests/ElementExtensionsTests.cs
src/CommunityToolkit.Maui.Markup.UnitTests/TextTests.cs
src/CommunityToolkit.Maui.Markup/ElementExtensions.cs

This PR fixes the `InvalidCastException` that is currently thrown by `.Text()` when used on the following Controls:
- `IButton`
- `MenuItem` (there is no `IMenuItem`)
- `IEditor`
- `IEntry`
- `ISearchBar`
- Fixes #55 
This is a temporary work-around that accommodates all of the current `IText` controls in .NET MAUI.
The proper solution is to create a Source Generator that generates a control-specific method for each `IText` control, similar to how we implemented the [`TextColorToGenerator` in CommunityToolkit.Maui](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs). The source generator would ensure that `.Text()` works for all future `IText` controls in .NET MAUI as well as custom `IText` controls created by …

Fix `.Text()` Bug

---

samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
samples/CommunityToolkit.Maui.Markup.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs

This PR updates `CommunityToolkit.Maui.Markup` to support [.NET MAUI RC2](https://github.com/dotnet/maui/releases/tag/6.0.300-rc.2).
This PR includes the following changes:
- Updates `CommunityToolkit.Maui.Markup.Sample` app
- Temporarily removes `CommunityToolkit.Maui` NuGet package until `CommunityToolkit.Maui-rc2` is released

Enable Support for .NET MAUI RC2

---

azure-pipelines.yml
samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
samples/CommunityToolkit.Maui.Markup.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/Android/AndroidManifest.xml
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/Android/MainApplication.cs
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/MacCatalyst/AppDelegate.cs
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/Windows/App.xaml.cs
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/Windows/Package.appxmanifest
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/iOS/AppDelegate.cs

This PR updates the Windows Sample app to match the [updated template](https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj):
- Update `SupportedOSPlatformVersion`
- Update `TargetPlatformMinVersion`
- Update `Package.appxmanifest`
This PR also updates `azurepipelines.yml` to leverage `VSBuild@1` for the `Build Markup Community Toolkit Sample` step. This ensures that the Windows Sample app is built during our CI Pipeline.

Update Sample App for .NET MAUI RC 2

---

src/CommunityToolkit.Maui.Markup.UnitTests/ViewExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/ViewExtensions.cs

This PR updates the XML Docs to use `<see ref.../>` to reference types.
This PR also adds missing unit tests for `LeftToRight.TextAlignmentExtensions` and `LeftToRight.LabelExtensions`.

Fix ViewExtensions XML Docs, Add Missing Unit Tests

---

src/CommunityToolkit.Maui.Markup.UnitTests/TextAlignmentExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/TextAlignmentExtensions.cs

This PR updates the following in `TextAlignmentExtensions.cs`:
- Rename `LeftToRight.LabelExtensions` to `LeftToRight.TextAlignmentExtensions`
- This aligns with the existing class `CommunityToolkit.Maui.Markup.TextAlignmentExtensions`
- The extension methods in this class all implement `T where T : ITextAlignment`
- Rename `RightToLeft.LabelExtensions` to `RightToLeft.TextAlignmentExtensions`
- This aligns with the existing class `CommunityToolkit.Maui.Markup.TextAlignmentExtensions`
- The extension methods in this class all implement `T where T : ITextAlignment`
- Update XML Docs to use `<see ref.../>` to reference types
This PR also adds missing unit tests for `LeftToRight.TextAlignmentExtensions` and `LeftToRight.LabelExtensions`

Fix TextAlignmentExtensions Class Names and XML Docs

---

src/CommunityToolkit.Maui.Markup.UnitTests/DefaultBindablePropertiesTests.cs
src/CommunityToolkit.Maui.Markup/BindableObjectExtensions.cs
src/CommunityToolkit.Maui.Markup/DefaultBindableProperties.cs

This PR fixes a bug in `.BindCommand()` that prevented the logic from working on .NET MAUI controls that inherit from a base class that implements `CommandProperty` and `CommandParameterProperty`.
The specific example raised in #82 demonstrates that `MenuFlyoutItem` doesn't implement `CommandProperty` and `CommandParameterProperty`, but its base class [`MenuItem` does](https://github.com/dotnet/maui/blob/e38582b53564b85398588e9ecaba43e325fa04fa/src/Controls/src/Core/MenuItem.cs#L16-L22).
The logic in `.BindCommand()` uses reflection to recursively search for `CommandProperty` and `CommandParameterProperty` in a class. If it doesn't find it, it will then search the base class. However, this line of code was preventing it from searching a base class once it discovered a `Microsoft.Maui.*` …

`.BindCommand()`: Search Base Types of `Microsoft.Maui.*` Classes for `CommandProperty` and `CommandParameterProperty`

---

.github/fabricbot.json

Proposals should be closed automatically by `msftbot` when moved to the `Closed` or `Completed` column in our [New Feature Proposals Project Board](https://github.com/CommunityToolkit/Maui/projects/1).
Due to a bug in the Boolean logic, `msftbot` has been incorrectly reopening Proposals that should remain closed:
```
// Previous Logic (with bug)
(`proposal` label || On New Feature Proposal project board || Title contains `[Proposal]`)
&& (!IsOpen)
&& (![Is in Closed Column] || ![Is in Completed Column]) // BUG: This would always resolve to `true` because the Proposal could never be in both columns simultaneously
// Previous Logic (with bug)
(`proposal` label || On New Feature Proposal project board || Title contains `[Proposal]`)
&& (!IsOpen)
&& !([Is in Closed Column] || [Is in Completed …
```

Fix MSFTBOT Bug Causing it to Reopen Completed/Closed Proposals

---

samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
samples/CommunityToolkit.Maui.Markup.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Markup.Sample/Services/HackerNewsApiService.cs

To demonstrate best practices for .NET MAUI apps that utilize HttpClient, this PR replaces the following NuGet Packages:
- `Refit` -> `Refit.HttpClientFactory`
- `Polly` -> `Microsoft.Extensions.Http.Polly`
Because .NET MAUI supports dependency injection, we can leverage `Refit.HttpClientFactory` to easily implement REST API requests and `Microsoft.Extensions.Http.Polly` to add automatic error handling policies. In the updated code below, when HttpClient fails it will now automatically retry to connect to the URL 3 times using an exponential backoff of 2<sup>n</sup> seconds. This is ideal for flaky mobile internet connections where a user's device may switch cellular towers or lose a Wifi connection.
```cs
builder.Services.AddRefitClient<IHackerNewsApi>()
.ConfigureHttpClient(client => …
```

[CommunityToolkit.Maui.Markup.Sample] Replace `Refit` + `Polly` with `Microsoft.Extensions.Http.Polly` and `Refit.HttpClientFactory`

---

samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsDetailPage.cs
samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsPage.cs
samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs
samples/CommunityToolkit.Maui.Markup.Sample/ViewModels/NewsDetailViewModel.cs
samples/CommunityToolkit.Maui.Markup.Sample/ViewModels/NewsViewModel.cs
samples/CommunityToolkit.Maui.Markup.Sample/ViewModels/SettingsViewModel.cs

This PR fixes the following build error:
> NewsViewModel.cs(15,15): Error CA1001: Type 'NewsViewModel' owns disposable field(s) 'insertIntoSortedCollectionSemaphore' but is not disposable (CA1001) (CommunityToolkit.Maui.Markup.Sample)
This PR also adds `sealed` to each Page + ViewModel class to reduce the complexity of the `IDisposable` implementation and to [improve performance](https://www.meziantou.net/performance-benefits-of-sealed-class.htm).

[Sample App] Add `IDisposable`

---

azure-pipelines.yml
samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
src/CommunityToolkit.Maui.Markup.SourceGenerators/Diagnostics/TextAlignmentDiagnostics.cs
src/CommunityToolkit.Maui.Markup.SourceGenerators/Extensions/CompilationExtensions.cs
src/CommunityToolkit.Maui.Markup.SourceGenerators/Extensions/NamespaceSymbolExtensions.cs
src/CommunityToolkit.Maui.Markup.SourceGenerators/SourceGenerators/TextAlignmentExtensionsGenerator.cs
src/CommunityToolkit.Maui.Markup.UnitTests/CommunityToolkit.Maui.Markup.UnitTests.csproj
src/CommunityToolkit.Maui.Markup.UnitTests/ICustomTextAlignment.cs
src/CommunityToolkit.Maui.Markup.UnitTests/TextAlignmentExtensionsTests.cs
src/CommunityToolkit.Maui.Markup.sln
src/CommunityToolkit.Maui.Markup/CommunityToolkit.Maui.Markup.csproj

This PR updates `TextAlignmentExtensionsGenerator` to support all user-generated types that implement `ITextAlignment`, and adds associated Unit Tests.
- Fixes #116 
The implementation of this PR is inspired by [`CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator`](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs).

Support all inherited `ITextAlignment` for `TextAlignmentExtensions`

---

README.md

This PR removes the duplicate, non-fluent, C# example from the README to match the update to the official docs: https://github.com/MicrosoftDocs/CommunityToolkit/pull/159

Remove Duplicated `ContentPage` Example

---

src/CommunityToolkit.Maui.Markup.UnitTests/BindableObjectExtensionsTests.cs
src/CommunityToolkit.Maui.Markup.UnitTests/ObjectExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/BindableObjectExtensions.cs
src/CommunityToolkit.Maui.Markup/ObjectExtensions.cs

This PR  removes the `BindableObject` constraint (`where T : BindableObject`) from `.Assign()` and `.Invoke()` extension methods.
```cs
public static TBindable Assign<TBindable, TVariable>(this TBindable bindable, out TVariable variable) 
where TBindable : BindableObject, TVariable;
public static TBindable Invoke<TBindable>(this TBindable bindable, Action<TBindable> action) 
where TBindable : BindableObject;
```
```cs
public static TAssignable Assign<TAssignable, TVariable>(this TAssignable assignable, out TVariable variable) 
where TAssignable : TVariable;
public static TAssignable Invoke<TAssignable>(this TAssignable assignable, Action<TAssignable> action);
// no constraint
```
- Fixes https://github.com/CommunityToolkit/Maui.Markup/issues/130

Remove `BindableObject` Constraint from `.Assign()` and `.Invoke()`

---

src/CommunityToolkit.Maui.Markup.UnitTests/Base/BaseMarkupTestFixture.cs
src/CommunityToolkit.Maui.Markup.UnitTests/TextAlignmentExtensionsTests.cs

This PR fixes tests that were being skipped instead of failing.
The [logs from the latest CI Build](https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=82056&view=logs&j=c44e3ce6-80b8-5090-9435-9627042472dc&t=dc770622-70f0-5084-e949-6d62de2aa47d&l=26) show that two tests were being skipped:
- `TextLeft`
- `TextRight`
The CI Build was still passing because the tests were using `Assume.That` which will skip the test when a failure occurs. 
This PR replaces `Assume.That` with `Assert.That`, and updates the TextAlignment tests to perform the tests without utilizing `TestPropertiesSet()` which requires the changing BindableProperty to be different from its default value.
This PR fixes 
The good news is that there is not a bug in `CommunityToolit.Maui.Markup`, rather the bug …

Fix TextAlignment Tests

---

Directory.Build.props
src/CommunityToolkit.Maui.Markup.UnitTests/ObjectExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/ObjectExtensions.cs

This PR adds Unit Tests to `ObjectExtensionsTests` to ensure derived types are supported by `.Assign()` and `.Invoke()`.
- Fixes #135 
- Technically, it doesn't "fix" the Issues, but rather confirms that we cannot reproduce the Issue
This PR does not change any code in the `CommunityToolkit.Maui.Markup` library.
This PR technically, it doesn't "fix" #135. Rather, it confirms that we cannot reproduce #135.
This PR also adds `<WarningsAsErrors>CS1710</WarningsAsErrors>` to avoid duplicate XML Comments

Update `ObjectExtensionsTests` to Include Derived Types

---

azure-pipelines.yml
global.json
samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
src/CommunityToolkit.Maui.Markup.SourceGenerators/CommunityToolkit.Maui.Markup.SourceGenerators.csproj
src/CommunityToolkit.Maui.Markup.UnitTests/CommunityToolkit.Maui.Markup.UnitTests.csproj
src/CommunityToolkit.Maui.Markup.UnitTests/GesturesExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/CommunityToolkit.Maui.Markup.csproj

This PR bumps `CommunityToolkit.Maui.Markup` to .NET 7
Added https://github.com/CommunityToolkit/Maui.Markup/labels/do%20not%20merge until .NET MAUI support for .NET 7 is promoted to Stable release.
- CommunityToolkit.Maui.Markup
- Change TFM to `.net7.0`
- CommunityToolkit.Maui.Markup.UnitTests
- Change TFM to `.net7.0`
- CommunityToolkit.Maui.Markup.Samples
- Change TFMs to `net7.0-android;net7.0-ios;net7.0-maccatalyst;net7.0-windows10.0.19041.0`

Add .NET 7 Support

---

Directory.Build.props
azure-pipelines.yml
samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/Tizen/Main.cs
samples/CommunityToolkit.Maui.Markup.Sample/Platforms/Tizen/tizen-manifest.xml

This PR adds Tizen support on Maui Markup Sample!
Tizen Workload is not included in the default MAUI Workloads, so it will break unless you install the Tizen Workload.
Therefore, [`TF_BUILD`](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) condition is set for adding `net7.0-tizen` as the TargetFrameworks so it is only included in the CI environment where Tizen workload environment is prepared.
- Fixes #137

Add Tizen TFM to Sample

---

src/CommunityToolkit.Maui.Markup.SourceGenerators/SourceGenerators/TextAlignmentExtensionsGenerator.cs

This PR changes generated classes, i.e. code generated by `TextAlignmentExtensionsGenerator`, from `public` to `internal`.
The bug in #158 is caused by two matching public classes being generated in both the .NET MAUI library (eg `net7.0-ios`) and the referenced class library (e.g. `net7.0`).
```
📦MyMauiSolution
┣ 📂MyMauiApp
- <TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
┗ 📂MyLibrary
- <TargetFramework>net7.0</TargetFramework>
```
- Fixes #158 
This aligns with a similar discussion on the `CommunityToolkit.Maui` repo: https://github.com/CommunityToolkit/Maui/discussions/756#discussioncomment-4125731

Make All Generated Classes `internal`

---

samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs
src/CommunityToolkit.Maui.Markup.UnitTests/BindingHelpers.cs
src/CommunityToolkit.Maui.Markup.UnitTests/CommunityToolkit.Maui.Markup.UnitTests.csproj
src/CommunityToolkit.Maui.Markup.UnitTests/TypedBindingExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/TypedBindingExtensions.cs

This PR adds support for `IValueConverter` with Typed Bindings extensions
- Fixes https://github.com/CommunityToolkit/Maui.Markup/issues/179
Allows the use of `IValueConverter` with the new Typed Bindings extensions, such as [`CommunityToolkit.Maui.Converters.ColorToHexRgbStringConverter` in the .NET MAUI Community Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/color-to-hex-rgba-string-converter):
```cs
new Label().Bind<Label, ViewModel, Color, string>(Label.TextProperty,
static (ViewModel viewModel) => viewModel.TextColor,
converter: new ColorToHexRgbStringConverter());
```

Add Support for `IValueConverter` in Typed Bindings Extensions

---

samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsDetailPage.cs
samples/CommunityToolkit.Maui.Markup.Sample/Pages/NewsPage.cs
src/CommunityToolkit.Maui.Markup.UnitTests/BindingHelpers.cs
src/CommunityToolkit.Maui.Markup.UnitTests/TypedBindingExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/GesturesExtensions.cs
src/CommunityToolkit.Maui.Markup/TypedBindingExtensions.cs
src/CommunityToolkit.Maui.Markup/TypedBindingsExtensions.Handlers.cs

This PR adds the following APIs which enables users to use `.BindCommand()` with Typed Bindings extensions:
```cs
/// <summary>Bind to the <typeparamref name="TBindable"/>'s default Command properties </summary>
public static TBindable BindCommand<TBindable, TCommandBindingContext>(
this TBindable bindable,
Expression<Func<TCommandBindingContext, ICommand>> getter,
Action<TCommandBindingContext, ICommand>? setter = null,
BindingMode mode = BindingMode.Default,
TCommandBindingContext? source = default) where TBindable : BindableObject;
/// <summary>Bind to the <typeparamref name="TBindable"/>'s default Command properties </summary>
public static TBindable BindCommand<TBindable, TCommandBindingContext>(
this TBindable bindable,
Func<TCommandBindingContext, ICommand> getter, …
```

Add `BindCommand` Support for Typed Bindings Extensions

---

Directory.Build.props

This PR enables `AccelerateBuildsInVisualStudio`, recently introduced in Visual Studio v17.5:
https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md
> The feature was added in 17.5 and is currently opt-in. It applies to SDK-style .NET projects only. It is simple to try, and in most cases will improve build times. Larger solutions will see greater gains.
>
>
> Visual Studio uses MSBuild to build .NET projects. There is some overhead associated with calling MSBuild to build each project, so Visual Studio uses a "fast up-to-date check" (FUTDC) to avoid calling MSBuild unless needed. This FUTDC can quickly determine if anything has changed in the project that would cause a build to be required. For more information, see [Up-to-date …

[Housekeeping] Enable `AccelerateBuildsInVisualStudio`

---

samples/CommunityToolkit.Maui.Markup.Sample/MauiProgram.cs
src/CommunityToolkit.Maui.Markup.SourceGenerators/SourceGenerators/TextAlignmentExtensionsGenerator.cs
src/CommunityToolkit.Maui.Markup.UnitTests/TextAlignmentExtensionsTests.cs

~~**Another suggested fix:** #206~~
~~(**ONLY ONE** of the PRs need to be merged)~~
- Fixes #182

Do not generate TextAlignment extension if it's already generated by base type

---

samples/CommunityToolkit.Maui.Markup.Sample/Pages/SettingsPage.cs
src/CommunityToolkit.Maui.Markup.UnitTests/AbsoluteLayoutExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/AbsoluteLayoutExtensions.cs

This Proposal adds two new APIs to `AbsoluteLayoutExtensions` and updates the functionality of the existing `.LayoutFlags()` API to add existing `AbsoluteLayoutFlags` instead of overwriting existing `AbsoluteLayoutFlags`.
```cs
public static TBindable ClearLayoutFlags<TBindable>(this TBindable bindable) where TBindable : BindableObject;
public static TBindable LayoutFlags<TBindable>(this TBindable bindable, params AbsoluteLayoutFlags[] flags) where TBindable : BindableObject;
```
The current functionality of `LayoutFlags` overwrites any existing `AbsoluteLayoutFlags` that are already defined by the `BindableObject`. 
For example, the resulting `AbosluteLayoutFlag` property of the `Label` in the following sample will be only `AbsoluteLayoutFlags.PositionProportional`, because the current …

Update AbsoluteLayout Flags Extensions

---

azure-pipelines.yml

While preparing a new release I found out that we are publishing NuGets from both the macOS _and_ the Windows build. But only the Windows build has all the target platforms we need and are the libraries that are signed with a certificate.
The reason we didn't discover this earlier is basically because we got lucky until now. The macOS build is faster than the Windows one. So the macOS build would finish in let's say 10 minutes and produce NuGets, but then Windows would finish a couple of minutes later and override those NuGets and those would be used by a potential release.
This worked fine, until now the macOS build failed and I had to retry it. Once retries, it succeeded, but this time overriding the NuGets (again!) from Windows to the macOS ones. And because of that they were blocked …

Publish NuGet artifacts only from Windows build

---

Directory.Build.props
azure-pipelines.yml
global.json
samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
src/CommunityToolkit.Maui.Markup.UnitTests/BindingHelpers.cs
src/CommunityToolkit.Maui.Markup.UnitTests/CommunityToolkit.Maui.Markup.UnitTests.csproj
src/CommunityToolkit.Maui.Markup.UnitTests/GesturesExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/CommunityToolkit.Maui.Markup.csproj
src/CommunityToolkit.Maui.Markup/DefaultBindableProperties.cs
src/CommunityToolkit.Maui.Markup/GesturesExtensions.TypedBindings.cs
src/CommunityToolkit.Maui.Markup/GesturesExtensions.cs

This PR implements .NET 8.0 in `CommunityToolkit.Maui.Markup`.

Port to .NET 8.0

---

src/CommunityToolkit.Maui.Markup/AppBuilderExtensions.cs

- Fixes https://github.com/CommunityToolkit/Maui.Markup/discussions/261

Ensure `RegisterReloadApplicationEventHandler` Runs in DEBUG Configuration

---

.editorconfig
Directory.Build.props
azure-pipelines.yml
samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
samples/CommunityToolkit.Maui.Markup.Sample/MauiProgram.cs

This PR replaces `Microsoft.Extensions.Http.Polly` with `Microsoft.Extensions.Http.Resilience`.
In .NET 8, Microsoft teamed up with the `App-vNext.Polly` team to create a more-performant version of `Polly`.  The new `Microsoft.Extensions.Http.Resilience` library uses the new, more performant version of `Polly`.
Meanwhile `[Microsoft.Extensions.Http.Polly](https://www.nuget.org/packages/Microsoft.Extensions.Http.Polly)` uses the older, less performant, version of `Polly` now rebranded as `Polly.Core.`
To ensure our Sample App adheres to best practices recommended for all .NET MAUI developers, we are upgrading `Microsoft.Extensions.Http.Polly` with `Microsoft.Extensions.Http.Resilience`.
More information is available in this .NET Blog Post: …

[Sample App] Add Microsoft.Extensions.Http.Resilience

---

src/CommunityToolkit.Maui.Markup.UnitTests/ApplicationTestHelpers.cs
src/CommunityToolkit.Maui.Markup.UnitTests/Mocks/MockApplication.cs
src/CommunityToolkit.Maui.Markup.UnitTests/Mocks/MockDispatcherProvider.cs
src/CommunityToolkit.Maui.Markup.UnitTests/Mocks/MockResourcesProvider.cs
src/CommunityToolkit.Maui.Markup.UnitTests/StyleTests.cs
src/CommunityToolkit.Maui.Markup/Style.cs

- Fixes https://github.com/CommunityToolkit/Maui.Markup/issues/274
This PR is still pending documentation. I will submit a PR to the docs once this PR has been approved.

Add `Style<T>` Constructor Overload

---

src/CommunityToolkit.Maui.Markup.Benchmarks/CommunityToolkit.Maui.Markup.Benchmarks.csproj
src/CommunityToolkit.Maui.Markup.UnitTests/CommunityToolkit.Maui.Markup.UnitTests.csproj
src/CommunityToolkit.Maui.Markup/CommunityToolkit.Maui.Markup.csproj

This PR removes the reference `Microsoft.Maui.Controls.Compatibility` NuGet Package, matching a [similar PR on `CommunityToolkit.Maui`](https://github.com/CommunityToolkit/Maui/pull/2006).

Remove `Microsoft.Maui.Controls.Compatibility` references

---

Directory.Build.props
samples/CommunityToolkit.Maui.Markup.Sample/AppShell.cs
samples/CommunityToolkit.Maui.Markup.Sample/CommunityToolkit.Maui.Markup.Sample.csproj
src/CommunityToolkit.Maui.Markup/CommunityToolkit.Maui.Markup.csproj
src/CommunityToolkit.Maui.Markup/GridRowsColumns.cs

This PR enables Full AOT for `CommunityToolkit.Maui.Markup` by adding `<IsAotCompatible>true</IsAotCompatible>`.
This PR promotes all of the Trimmer + AOT analyzer warnings to errors in `<warningsaserrors>` inside `Directory.Build.props` to ensure we don't accidentally inject non-AOT Safe code in future PRs.
This PR also enables `<PublushAot>` for Release builds of `CommunityToolkit.Maui.Markup.Sample` to ensure our sample continues to run nominally while using AOT and  does not break in future releases.

Enable AOT Support

---

src/CommunityToolkit.Maui.Markup.UnitTests/GesturesExtensionsTests.cs
src/CommunityToolkit.Maui.Markup/GesturesExtensions.TypedBindings.cs
src/CommunityToolkit.Maui.Markup/GesturesExtensions.cs

This PR adds string-based Gesture Extensions that were mistakenly removed in v5.0.0.
String-based bindings are still valid in .NET MAUI 9.0.0, however they are not trim-safe.
Added `[RequiresUnreferencedCode("Using bindings with string paths is not trim safe. Use expression-based binding instead.")]` because string-based bingings are not trim-safe.
Moved Typed Bindings Gesture Extensions to `GesturesExtensions.TypedBindings.cs`

Add String-based Gesture Extensions
